/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import javax.swing.ImageIcon;

/**
 *
 * @author Luis Estrada
 */
public class frmMenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmMenuPrincipal
     */
    public frmMenuPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_menuPrincipal = new java.awt.Panel();
        btn_ClienteMenu = new javax.swing.JButton();
        btn_PuntosMenu = new javax.swing.JButton();
        btn_ReportesMenu = new javax.swing.JButton();
        btn_configuracion = new javax.swing.JButton();
        jl_tituloMenuPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal del Sistema de Puntos");
        setMaximumSize(new java.awt.Dimension(679, 433));
        setMinimumSize(new java.awt.Dimension(679, 433));
        setName("Menu Princial Sistema de Puntos"); // NOI18N
        setPreferredSize(new java.awt.Dimension(679, 433));
        getContentPane().setLayout(null);

        panel_menuPrincipal.setLayout(null);

        btn_ClienteMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/cliente v2.png"))); // NOI18N
        btn_ClienteMenu.setText("Cliente");
        btn_ClienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ClienteMenuActionPerformed(evt);
            }
        });
        panel_menuPrincipal.add(btn_ClienteMenu);
        btn_ClienteMenu.setBounds(40, 110, 220, 70);

        btn_PuntosMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/gestion_de_puntos v2.png"))); // NOI18N
        btn_PuntosMenu.setText("Puntos");
        btn_PuntosMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PuntosMenuActionPerformed(evt);
            }
        });
        panel_menuPrincipal.add(btn_PuntosMenu);
        btn_PuntosMenu.setBounds(350, 110, 220, 70);

        btn_ReportesMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/reportes v2.png"))); // NOI18N
        btn_ReportesMenu.setText("Reportes");
        btn_ReportesMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ReportesMenuActionPerformed(evt);
            }
        });
        panel_menuPrincipal.add(btn_ReportesMenu);
        btn_ReportesMenu.setBounds(40, 230, 220, 70);

        btn_configuracion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/administrador.png"))); // NOI18N
        btn_configuracion.setText("Configuración");
        btn_configuracion.setToolTipText("");
        btn_configuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_configuracionActionPerformed(evt);
            }
        });
        panel_menuPrincipal.add(btn_configuracion);
        btn_configuracion.setBounds(360, 230, 220, 70);

        jl_tituloMenuPrincipal.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jl_tituloMenuPrincipal.setText("Sistema de Puntos Farmacia ");
        panel_menuPrincipal.add(jl_tituloMenuPrincipal);
        jl_tituloMenuPrincipal.setBounds(50, 20, 526, 40);

        getContentPane().add(panel_menuPrincipal);
        panel_menuPrincipal.setBounds(40, 50, 600, 340);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_configuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_configuracionActionPerformed

        frmLoginModuloConfiguracion ver=new frmLoginModuloConfiguracion();
            ver.setVisible(true); // visible ventana del objeto
         //   this.setVisible(false); // ocultar
    }//GEN-LAST:event_btn_configuracionActionPerformed

    private void btn_ReportesMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ReportesMenuActionPerformed
         frmSubMenuReporte ver=new frmSubMenuReporte();
            ver.setVisible(true); // visible ventana del objeto
           // this.setVisible(false); // ocultar

    }//GEN-LAST:event_btn_ReportesMenuActionPerformed

    private void btn_ClienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ClienteMenuActionPerformed
        frmConsultarCliente ver=new frmConsultarCliente();
            ver.setVisible(true); // visible ventana del objeto
       //     this.setVisible(false); // ocultar
        
    }//GEN-LAST:event_btn_ClienteMenuActionPerformed

    private void btn_PuntosMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PuntosMenuActionPerformed
        frmSubMenuPuntos ver=new frmSubMenuPuntos();
            ver.setVisible(true); // visible ventana del objeto
         //   this.setVisible(false); // ocultar
        
    }//GEN-LAST:event_btn_PuntosMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ClienteMenu;
    private javax.swing.JButton btn_PuntosMenu;
    private javax.swing.JButton btn_ReportesMenu;
    private javax.swing.JButton btn_configuracion;
    private javax.swing.JLabel jl_tituloMenuPrincipal;
    private java.awt.Panel panel_menuPrincipal;
    // End of variables declaration//GEN-END:variables
}
