/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import Clases.Persona;
import Clases.Validar;
import Clases.Zona;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Bayron Ayala y Roger Colindres
 */
public class frmSubMenuCliente extends javax.swing.JFrame {

    /**
     * Creates new form frmSubMenuCliente
     */
    public frmSubMenuCliente() {
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
        //cargarZonas();
        v.ValidarSoloLetras(txt_primerNombre);
        v.ValidarSoloLetras(txt_segundoNombre);
        v.ValidarSoloLetras(txt_primerApellido);
        v.ValidarSoloLetras(txt_segundoApellido);
        v.ValidarTelefono(txt_telefono1);
        v.ValidarTelefono(txt_telefono2);
        v.ValidarTelefono(txt_telefono3);
        v.ValidarIdentidad(txt_identidad);
        v.limitarCaracteres(txt_telefono1, 13);
        v.limitarCaracteres(txt_telefono2, 13);
        v.limitarCaracteres(txt_telefono3, 13);
        v.limitarCaracteres(txt_identidad, 15);
    }

    Validar v = new Validar();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RG_genero = new javax.swing.ButtonGroup();
        jpanel_AreaSubMenu = new javax.swing.JPanel();
        jpanel_datos1 = new javax.swing.JPanel();
        jL_primerNombre = new javax.swing.JLabel();
        jL_segundoNombre = new javax.swing.JLabel();
        jL_primerApellido = new javax.swing.JLabel();
        jL_segundoApellido = new javax.swing.JLabel();
        jL_identidad = new javax.swing.JLabel();
        jL_sexo = new javax.swing.JLabel();
        jL_telefono = new javax.swing.JLabel();
        txt_primerNombre = new javax.swing.JTextField();
        txt_segundoNombre = new javax.swing.JTextField();
        txt_primerApellido = new javax.swing.JTextField();
        txt_segundoApellido = new javax.swing.JTextField();
        txt_identidad = new javax.swing.JTextField();
        txt_telefono1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_telefono2 = new javax.swing.JTextField();
        txt_telefono3 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jL_email = new javax.swing.JLabel();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        btn_editarCliente = new javax.swing.JButton();
        btn_desactivarCliente = new javax.swing.JButton();
        btn_imprimirDireccion = new javax.swing.JButton();
        btn_imprimirPuntos = new javax.swing.JButton();
        jpanel_datos2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_puntosRegis = new javax.swing.JTextField();
        jL_vencimiento = new javax.swing.JLabel();
        txt_vencimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_puntoRifa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jD_fechaNac = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_datalleDireccion = new javax.swing.JTextArea();
        jC_zona = new javax.swing.JComboBox<>();
        btn_habilitarcliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestion Cliente");
        setMaximumSize(new java.awt.Dimension(833, 509));
        setMinimumSize(new java.awt.Dimension(833, 509));
        setName("Menu Cliente"); // NOI18N
        setPreferredSize(new java.awt.Dimension(833, 509));

        jpanel_AreaSubMenu.setPreferredSize(new java.awt.Dimension(100, 500));
        jpanel_AreaSubMenu.setLayout(null);

        jL_primerNombre.setText("Primer Nombre:");

        jL_segundoNombre.setText("Segundo Nombre:");

        jL_primerApellido.setText("Primer Apellido:");

        jL_segundoApellido.setText("Segundo Apellido:");

        jL_identidad.setText("Identidad:");

        jL_sexo.setText("Sexo :");

        jL_telefono.setText("Telefono 1:");

        txt_primerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_primerNombreKeyPressed(evt);
            }
        });

        txt_segundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_segundoNombreActionPerformed(evt);
            }
        });
        txt_segundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_segundoNombreKeyPressed(evt);
            }
        });

        txt_primerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_primerApellidoKeyPressed(evt);
            }
        });

        txt_segundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_segundoApellidoKeyPressed(evt);
            }
        });

        txt_identidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_identidadKeyPressed(evt);
            }
        });

        txt_telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono1KeyPressed(evt);
            }
        });

        jLabel1.setText("Telefono 2:");

        jLabel2.setText("Telefono 3:");

        txt_telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono2KeyPressed(evt);
            }
        });

        txt_telefono3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono3KeyPressed(evt);
            }
        });

        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });

        jL_email.setText("Email:");

        RG_genero.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("F");
        jRadioButtonFemenino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonFemeninoKeyPressed(evt);
            }
        });

        RG_genero.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("M");
        jRadioButtonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_datos1Layout = new javax.swing.GroupLayout(jpanel_datos1);
        jpanel_datos1.setLayout(jpanel_datos1Layout);
        jpanel_datos1Layout.setHorizontalGroup(
            jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_datos1Layout.createSequentialGroup()
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jL_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jL_primerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_primerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jL_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_telefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addComponent(jL_email, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_datos1Layout.createSequentialGroup()
                                .addComponent(jRadioButtonFemenino)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jRadioButtonMasculino))
                            .addComponent(txt_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpanel_datos1Layout.createSequentialGroup()
                        .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jL_segundoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                            .addComponent(jL_segundoApellido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(41, 41, 41)
                        .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_segundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_segundoNombre, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(40, 40, 40))
        );
        jpanel_datos1Layout.setVerticalGroup(
            jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_datos1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_primerNombre)
                    .addComponent(txt_primerNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_segundoNombre)
                    .addComponent(txt_segundoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_primerApellido)
                    .addComponent(txt_primerApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_segundoApellido)
                    .addComponent(txt_segundoApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_identidad)
                    .addComponent(txt_identidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_sexo)
                    .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonFemenino)
                        .addComponent(jRadioButtonMasculino)))
                .addGap(7, 7, 7)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_telefono)
                    .addComponent(txt_telefono1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txt_telefono2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txt_telefono3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jpanel_datos1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jL_email)
                    .addComponent(txt_email, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jpanel_AreaSubMenu.add(jpanel_datos1);
        jpanel_datos1.setBounds(50, 100, 370, 350);

        btn_editarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/modificar.png"))); // NOI18N
        btn_editarCliente.setText("Editar");
        btn_editarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_editarCliente.setMaximumSize(new java.awt.Dimension(90, 55));
        btn_editarCliente.setMinimumSize(new java.awt.Dimension(90, 55));
        btn_editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarClienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_editarCliente);
        btn_editarCliente.setBounds(10, 10, 100, 50);

        btn_desactivarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/inhabilitar.png"))); // NOI18N
        btn_desactivarCliente.setText("Deshabilitar");
        btn_desactivarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_desactivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desactivarClienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_desactivarCliente);
        btn_desactivarCliente.setBounds(240, 10, 110, 50);

        btn_imprimirDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/dato entrega.png"))); // NOI18N
        btn_imprimirDireccion.setText("Imprimir dirección");
        btn_imprimirDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_imprimirDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirDireccionActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_imprimirDireccion);
        btn_imprimirDireccion.setBounds(360, 10, 160, 50);

        btn_imprimirPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/dato puntos.png"))); // NOI18N
        btn_imprimirPuntos.setText("Imprimir puntos");
        btn_imprimirPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_imprimirPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirPuntosActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_imprimirPuntos);
        btn_imprimirPuntos.setBounds(530, 10, 130, 50);

        jLabel9.setText("Puntos Regis:");

        txt_puntosRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntosRegisActionPerformed(evt);
            }
        });

        jL_vencimiento.setText("Vencimiento:");

        txt_vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vencimientoActionPerformed(evt);
            }
        });

        jLabel11.setText("Puntos rifa:");

        txt_puntoRifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntoRifaActionPerformed(evt);
            }
        });

        jLabel3.setText("Fecha Nacimiento");

        jD_fechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jD_fechaNacKeyPressed(evt);
            }
        });

        jLabel4.setText("Zona");

        jLabel5.setText("Dirección");

        txt_datalleDireccion.setColumns(20);
        txt_datalleDireccion.setRows(5);
        txt_datalleDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_datalleDireccionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_datalleDireccion);

        jC_zona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_zonaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jpanel_datos2Layout = new javax.swing.GroupLayout(jpanel_datos2);
        jpanel_datos2.setLayout(jpanel_datos2Layout);
        jpanel_datos2Layout.setHorizontalGroup(
            jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_datos2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpanel_datos2Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_puntoRifa, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos2Layout.createSequentialGroup()
                        .addComponent(jL_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpanel_datos2Layout.createSequentialGroup()
                        .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpanel_datos2Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txt_puntosRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanel_datos2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jpanel_datos2Layout.createSequentialGroup()
                        .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jD_fechaNac, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE)
                            .addComponent(jC_zona, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(10, 50, Short.MAX_VALUE))
        );
        jpanel_datos2Layout.setVerticalGroup(
            jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanel_datos2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jD_fechaNac, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jC_zona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(txt_puntosRegis, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_vencimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL_vencimiento))
                .addGap(11, 11, 11)
                .addGroup(jpanel_datos2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_puntoRifa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(37, 37, 37))
        );

        jpanel_AreaSubMenu.add(jpanel_datos2);
        jpanel_datos2.setBounds(420, 104, 370, 340);

        btn_habilitarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/habilitar.png"))); // NOI18N
        btn_habilitarcliente.setText("Habilitar");
        btn_habilitarcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_habilitarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_habilitarclienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_habilitarcliente);
        btn_habilitarcliente.setBounds(120, 10, 110, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpanel_AreaSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jpanel_AreaSubMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarClienteActionPerformed

        //Validar que no esten vacios los campos requeridos
        if (txt_primerNombre.getText().isEmpty() || txt_primerApellido.getText().isEmpty() || txt_identidad.getText().isEmpty()
            || txt_telefono1.getText().isEmpty() || jD_fechaNac.getCalendar() == null
            || jC_zona.getSelectedItem() == null || (jRadioButtonMasculino.isSelected() == false && jRadioButtonFemenino.isSelected() == false)) {

            JOptionPane.showMessageDialog(this, "Se dejaron vacios campos que son obligatorios", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                //PREPARO LA FECHA PARA ENVIARLA
                java.sql.Date fechaNac = new java.sql.Date(jD_fechaNac.getDate().getTime());

                //Consulto el id de la zona que eligio el usuario para registrarla en la tabla clientes
                ResultSet respuesta = Zona.consultarIdZona((String) jC_zona.getSelectedItem());
                int idZona = 0;

                while (respuesta.next()) {
                    idZona = respuesta.getInt(1);
                }

                //Verificar el sexo seleccionado
                String sexo = "";
                if (jRadioButtonMasculino.isSelected() == true) {
                    sexo = "M";
                } else if (jRadioButtonFemenino.isSelected() == true) {
                    sexo = "F";
                }

                Procedimientos.ProcedimientosCliente.actualizarCliente(txt_primerNombre.getText(), txt_segundoNombre.getText(),
                    txt_primerApellido.getText(), txt_segundoApellido.getText(), txt_identidad.getText(), txt_email.getText(),
                    sexo, fechaNac, txt_telefono1.getText(), txt_telefono2.getText(), txt_telefono3.getText(),
                    idZona, txt_datalleDireccion.getText(), Integer.parseInt(txt_puntosRegis.getText()),
                    txt_vencimiento.getText(), Integer.parseInt(txt_puntoRifa.getText()),
                    Integer.parseInt(id.getText())
                );

                //Limpiar los campos
                txt_primerNombre.setText("");
                txt_segundoNombre.setText("");
                txt_primerApellido.setText("");
                txt_segundoApellido.setText("");
                txt_identidad.setText("");
                txt_email.setText("");
                txt_telefono1.setText("");
                txt_telefono2.setText("");
                txt_telefono3.setText("");
                jRadioButtonMasculino.setSelected(false);
                jRadioButtonFemenino.setSelected(false);
                jD_fechaNac.setCalendar(null);
                jC_zona.setSelectedIndex(0);
                txt_datalleDireccion.setText("");
                txt_primerNombre.requestFocus();
                txt_segundoNombre.requestFocus();
                txt_primerApellido.requestFocus();
                txt_segundoApellido.requestFocus();
                txt_identidad.requestFocus();
                txt_email.requestFocus();
                txt_telefono1.requestFocus();
                txt_telefono2.requestFocus();
                txt_telefono3.requestFocus();
                jD_fechaNac.requestFocus();
                jC_zona.requestFocus();
                txt_primerNombre.requestFocus();

                JOptionPane.showMessageDialog(this, "Registro actualizado");

            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_btn_editarClienteActionPerformed

    public void cargarZonas(String zona) {
        ResultSet zonas = Zona.mostrarZonas();
        //LLenamos nuestro ComboBox
        jC_zona.addItem(zona);
        try {
            while (zonas.next()) {
                if (!zonas.getString("zona").equals(zona)) {
                    jC_zona.addItem(zonas.getString("zona"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmRegistroClientes.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void btn_imprimirPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirPuntosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_imprimirPuntosActionPerformed

    private JTextField id = new JTextField();

    //Metodo para llenar los campos     
    public void llenarCampos(String pnombre, String snombre, String papellido, String sapellido, String identidad,
            String sexo, String telefono1, String telefono2, String telefono3, String correo,
            Date fechaNac, String detalleDireccion, String puntos_actuales, String puntos_rifa,
            String fechaVencimiento, String id) {
        this.txt_primerNombre.setText(pnombre);
        this.txt_segundoNombre.setText(snombre);
        this.txt_primerApellido.setText(papellido);
        this.txt_segundoApellido.setText(sapellido);
        this.txt_identidad.setText(identidad);
        if ("M".equals(sexo)) {
            this.jRadioButtonMasculino.setSelected(true);
        } else {
            this.jRadioButtonFemenino.setSelected(true);
        }
        this.txt_telefono1.setText(telefono1);
        this.txt_telefono2.setText(telefono2);
        this.txt_telefono3.setText(telefono3);
        this.txt_email.setText(correo);
        this.jD_fechaNac.setDate(fechaNac);
        this.txt_datalleDireccion.setText(detalleDireccion);
        this.txt_puntosRegis.setText(puntos_actuales);
        this.txt_puntoRifa.setText(puntos_rifa);
        this.txt_vencimiento.setText(fechaVencimiento);
        this.id.setText(id);
    }

    private void txt_puntosRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntosRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntosRegisActionPerformed

    private void btn_desactivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desactivarClienteActionPerformed
        /*int pregunta = JOptionPane.showConfirmDialog(null, "¿Deseas deshabilitar a este cliente?");
        if (pregunta == 0) {
            try {
                Procedimientos.ProcedimientosCliente.deshabilitarCliente(txt_identidad.getText());
                JOptionPane.showMessageDialog(null, "El cliente ha sido deshabilitado");
            } catch (SQLException e) {

            }
        } else if (pregunta == 1) {
            JOptionPane.showMessageDialog(null, "El cliente no se ha deshabilitado");
        } else {
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
        }*/

    }//GEN-LAST:event_btn_desactivarClienteActionPerformed

    private void txt_segundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_segundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_segundoNombreActionPerformed

    private void txt_vencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vencimientoActionPerformed

    private void txt_puntoRifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntoRifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntoRifaActionPerformed

    private void jRadioButtonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinoActionPerformed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        if (!"".equals(txt_email.getText())) {
            if (v.validarCorreo(txt_email)) {
                jD_fechaNac.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Correo inválido", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                txt_email.requestFocus();
            }
        } else {
            jD_fechaNac.requestFocus();
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jD_fechaNac.requestFocus();
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void txt_primerNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_segundoNombre.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(txt_primerNombre);
        }
    }//GEN-LAST:event_txt_primerNombreKeyPressed

    private void txt_segundoNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_primerApellido.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(txt_segundoNombre);
        }
    }//GEN-LAST:event_txt_segundoNombreKeyPressed

    private void txt_primerApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerApellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_segundoApellido.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(txt_primerApellido);
        }
    }//GEN-LAST:event_txt_primerApellidoKeyPressed

    private void txt_segundoApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoApellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_identidad.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(txt_segundoApellido);
        }
    }//GEN-LAST:event_txt_segundoApellidoKeyPressed

    private void txt_identidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jRadioButtonFemenino.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(txt_identidad);
        }
    }//GEN-LAST:event_txt_identidadKeyPressed

    private void jRadioButtonFemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonFemeninoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_telefono1.requestFocus();
        }
    }//GEN-LAST:event_jRadioButtonFemeninoKeyPressed

    private void txt_telefono1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_telefono2.requestFocus();
        }
    }//GEN-LAST:event_txt_telefono1KeyPressed

    private void txt_telefono2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_telefono3.requestFocus();
        }
    }//GEN-LAST:event_txt_telefono2KeyPressed

    private void txt_telefono3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_email.requestFocus();
        }
    }//GEN-LAST:event_txt_telefono3KeyPressed

    private void jD_fechaNacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jD_fechaNacKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jC_zona.requestFocus();
        }
    }//GEN-LAST:event_jD_fechaNacKeyPressed

    private void jC_zonaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_zonaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_datalleDireccion.requestFocus();
        }
    }//GEN-LAST:event_jC_zonaKeyPressed

    private void txt_datalleDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_datalleDireccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            txt_primerNombre.requestFocus();
        }
    }//GEN-LAST:event_txt_datalleDireccionKeyPressed

    private void btn_habilitarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_habilitarclienteActionPerformed
        /*int pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea habilitar este cliente?");
        if (pregunta == 0) {
            try {
                Procedimientos.ProcedimientosCliente.habilitarCliente();
                JOptionPane.showMessageDialog(null, "El cliente ha sido habilitado");
            } catch (SQLException e) {

            }
        } else if (pregunta == 1) {
            JOptionPane.showMessageDialog(null, "El cliente no ha sido habilitado");
        } else {
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
        }*/
    }//GEN-LAST:event_btn_habilitarclienteActionPerformed

    private void btn_imprimirDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirDireccionActionPerformed
        int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea imprimir direccion?", "Confirmar impresión",
                JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (eleccion == JOptionPane.NO_OPTION) {
            
        } else {

            frmImprimirDireccion dir = new frmImprimirDireccion();
            dir.setVisible(true);

            String nombre = this.txt_primerNombre.getText() + " " + this.txt_segundoNombre.getText()
                    + " " + this.txt_primerApellido.getText() + " " + this.txt_segundoApellido.getText(),
                    telefono = this.txt_telefono1.getText(),
                    sexo = null,
                    direccion = this.txt_datalleDireccion.getText();

            if (this.jRadioButtonMasculino.isSelected() == true) {
                sexo = "Masculino";
            } else {
                sexo = "Femenino";
            }

            dir.cargarDatos(nombre, telefono, sexo, direccion);
        }
    }//GEN-LAST:event_btn_imprimirDireccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSubMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSubMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSubMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSubMenuCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSubMenuCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup RG_genero;
    private javax.swing.JButton btn_desactivarCliente;
    private javax.swing.JButton btn_editarCliente;
    private javax.swing.JButton btn_habilitarcliente;
    private javax.swing.JButton btn_imprimirDireccion;
    private javax.swing.JButton btn_imprimirPuntos;
    private javax.swing.JComboBox<String> jC_zona;
    private com.toedter.calendar.JDateChooser jD_fechaNac;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_identidad;
    private javax.swing.JLabel jL_primerApellido;
    private javax.swing.JLabel jL_primerNombre;
    private javax.swing.JLabel jL_segundoApellido;
    private javax.swing.JLabel jL_segundoNombre;
    private javax.swing.JLabel jL_sexo;
    private javax.swing.JLabel jL_telefono;
    private javax.swing.JLabel jL_vencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel_AreaSubMenu;
    private javax.swing.JPanel jpanel_datos1;
    private javax.swing.JPanel jpanel_datos2;
    private javax.swing.JTextArea txt_datalleDireccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_identidad;
    private javax.swing.JTextField txt_primerApellido;
    private javax.swing.JTextField txt_primerNombre;
    private javax.swing.JTextField txt_puntoRifa;
    private javax.swing.JTextField txt_puntosRegis;
    private javax.swing.JTextField txt_segundoApellido;
    private javax.swing.JTextField txt_segundoNombre;
    private javax.swing.JTextField txt_telefono1;
    private javax.swing.JTextField txt_telefono2;
    private javax.swing.JTextField txt_telefono3;
    private javax.swing.JTextField txt_vencimiento;
    // End of variables declaration//GEN-END:variables
}
