/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//librerias para encripotar e desenccriptar
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.Cipher;
import javax.crypto.SecretKey;
import javax.crypto.spec.SecretKeySpec;
import org.apache.commons.codec.binary.Base64;

/**
 *
 * @author Luis Estrada
 */
public class mdl_cambiar_contrasena extends java.awt.Dialog {
    private String usuario;
    /**
     * Creates new form mdl_cambiar_contrasena
     */
    public mdl_cambiar_contrasena(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
        lblConfirmacion.setVisible(false);
        cbxContrasenaActual.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_cambiar_pass = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblConfirmacion = new javax.swing.JLabel();
        cbxContrasenaActual = new javax.swing.JLabel();
        txt_pass_actual = new javax.swing.JPasswordField();
        txt_pass_nuevo = new javax.swing.JPasswordField();
        txt_pass_nuevo_confirmar = new javax.swing.JPasswordField();
        cbxActual = new javax.swing.JCheckBox();
        cbxNueva = new javax.swing.JCheckBox();
        cbxNueva2 = new javax.swing.JCheckBox();

        setMaximumSize(new java.awt.Dimension(648, 417));
        setMinimumSize(new java.awt.Dimension(648, 417));
        setTitle("Cambiar contraseña del sistema ");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel1.setLayout(null);

        btn_cambiar_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/guardar.png"))); // NOI18N
        btn_cambiar_pass.setText("Cambiar ");
        btn_cambiar_pass.setToolTipText("");
        btn_cambiar_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cambiar_passActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cambiar_pass);
        btn_cambiar_pass.setBounds(250, 330, 140, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Cambiar  Contraseña");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(210, 40, 260, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Contraseñan actual:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 130, 150, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Contraseña nueva:");
        jLabel3.setToolTipText("");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 190, 140, 20);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Confirmar contraseña nueva: ");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 250, 210, 17);

        lblConfirmacion.setText("No coinciden las contraseñas");
        jPanel1.add(lblConfirmacion);
        lblConfirmacion.setBounds(270, 280, 310, 16);

        cbxContrasenaActual.setText("Contraseña actual no coincide");
        jPanel1.add(cbxContrasenaActual);
        cbxContrasenaActual.setBounds(270, 160, 200, 16);
        jPanel1.add(txt_pass_actual);
        txt_pass_actual.setBounds(220, 130, 320, 22);
        jPanel1.add(txt_pass_nuevo);
        txt_pass_nuevo.setBounds(220, 190, 320, 22);
        jPanel1.add(txt_pass_nuevo_confirmar);
        txt_pass_nuevo_confirmar.setBounds(220, 250, 320, 22);

        cbxActual.setText("Ver");
        cbxActual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxActualActionPerformed(evt);
            }
        });
        jPanel1.add(cbxActual);
        cbxActual.setBounds(550, 130, 50, 24);

        cbxNueva.setText("Ver");
        cbxNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNuevaActionPerformed(evt);
            }
        });
        jPanel1.add(cbxNueva);
        cbxNueva.setBounds(550, 190, 60, 24);

        cbxNueva2.setText("Ver");
        cbxNueva2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxNueva2ActionPerformed(evt);
            }
        });
        jPanel1.add(cbxNueva2);
        cbxNueva2.setBounds(550, 250, 60, 24);

        add(jPanel1);
        jPanel1.setBounds(0, 0, 650, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private boolean isPasswordCorrect(char[] j1,char[] j2) {
        boolean valor = false;
        int puntero = 0;
        if (j1.length != j2.length){
            valor = false;
        }
        else{
            while((!valor)&&(puntero < j1.length)){
                if (j1[puntero] != j2[puntero]){
                valor = false;
                }
                else{
                    valor = true;
                }
            }
        }
        return valor;
    }
    
    private void btn_cambiar_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cambiar_passActionPerformed
        String contrasenaNueva="";
        String contrasenaActual="";
        boolean respuesta=false;
        if (txt_pass_actual.getPassword().equals(null)|| txt_pass_nuevo.getPassword().equals(null) || txt_pass_nuevo_confirmar.getPassword().equals(null)){
            JOptionPane.showMessageDialog(null, "No debe dejar campos vacios.");
        }else{
            
            try {
                contrasenaNueva = Clases.encriptarContrasena.encriptar(String.valueOf(txt_pass_nuevo.getPassword()));
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(mdl_cambiar_contrasena.class.getName()).log(Level.SEVERE, null, ex);
            }
            try {
                contrasenaActual = Clases.encriptarContrasena.encriptar(String.valueOf(txt_pass_actual.getPassword()));
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(mdl_cambiar_contrasena.class.getName()).log(Level.SEVERE, null, ex);
            }


            if( isPasswordCorrect(txt_pass_nuevo.getPassword(),txt_pass_nuevo_confirmar.getPassword()) ){
                try {
                    respuesta = verificarContraseniaActual(contrasenaActual);
                } catch (NoSuchAlgorithmException ex) {
                    Logger.getLogger(mdl_cambiar_contrasena.class.getName()).log(Level.SEVERE, null, ex);
                }
                if (respuesta){
                    //String sql="";
                    String sql = "UPDATE Admin\n" +
                        "SET contrasena = '"+ contrasenaNueva +"'\n" +
                        "WHERE usuario = '"+ this.usuario +"' ";
                    int filasAfectadas=0;
                    try {
                        //realizar el UPDATE sin problemas
                        Statement s = Conexion.Conexion.getConexion().createStatement();
                        //Guardamos las filas afectadas por el UPDATE
                        filasAfectadas = s.executeUpdate(sql);
                        //Realizamos commit de la instruccion SQL
                        Conexion.Conexion.getConexion().commit();
                        //Cerramos la conexion
                        s.close();
                    } catch (SQLException ex) {
                        Logger.getLogger(mdl_cambiar_contrasena.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (filasAfectadas == 1){
                        JOptionPane.showMessageDialog(this, "La contraseña ha sido actualizada.");
                    } else{
                        JOptionPane.showMessageDialog(this, "No se ha podido actualizar la contraseña.");
                    }
                }else {
                    cbxContrasenaActual.setVisible(true);
                    cbxContrasenaActual.setForeground(Color.red);
                }

            }else {
                lblConfirmacion.setVisible(true);
                lblConfirmacion.setForeground(Color.red);
            }
        }       
    }//GEN-LAST:event_btn_cambiar_passActionPerformed

    private void cbxActualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxActualActionPerformed
        /*char i = txt_pass_actual.getEchoChar();
        boolean a = true;
        if (a) {  // a es una variable boolean en true
            txt_pass_actual.setEchoChar((char)0); // este método es el que hace visible el texto del jPasswordField
            a = false;
        } else {
            txt_pass_actual.setEchoChar(i); // i es el char
            a = true;
        }*/
        if (cbxActual.isSelected()) {
            txt_pass_actual.setEchoChar((char)0); //password = JPasswordField
         } else {
            txt_pass_actual.setEchoChar('*');
         }
    }//GEN-LAST:event_cbxActualActionPerformed

    private void cbxNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNuevaActionPerformed
        if (cbxNueva.isSelected()) {
            txt_pass_nuevo.setEchoChar((char)0); //password = JPasswordField
         } else {
            txt_pass_nuevo.setEchoChar('*');
         }
    }//GEN-LAST:event_cbxNuevaActionPerformed

    private void cbxNueva2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxNueva2ActionPerformed
        if (cbxNueva2.isSelected()) {
            txt_pass_nuevo_confirmar.setEchoChar((char)0); //password = JPasswordField
         } else {
            txt_pass_nuevo_confirmar.setEchoChar('*');
         }
    }//GEN-LAST:event_cbxNueva2ActionPerformed

    public void recibirUsuario(String user){
        this.usuario = user;
    }
    
    
    
    public boolean verificarContraseniaActual(String pass) throws NoSuchAlgorithmException{
        int conteo = 0;
        boolean c = false;
        String sql = "Select COUNT(*) from Admin where usuario='" + this.usuario + "' and contrasena ='" 
                +pass + "';";
        ResultSet res = Conexion.Conexion.consulta(sql);
        try{
            while (res.next()){
                conteo = res.getInt(1);
            }            
        }catch(SQLException e){
            System.out.println(e);
        }
        
        if (conteo !=1){
            c = false;
            JOptionPane.showMessageDialog(null, "La contraseña actual no es valida.");
        }
        else if (conteo == 1 ){
             c = true;
        }
        return c;
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_cambiar_contrasena dialog = new mdl_cambiar_contrasena(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cambiar_pass;
    private javax.swing.JCheckBox cbxActual;
    private javax.swing.JLabel cbxContrasenaActual;
    private javax.swing.JCheckBox cbxNueva;
    private javax.swing.JCheckBox cbxNueva2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblConfirmacion;
    private javax.swing.JPasswordField txt_pass_actual;
    private javax.swing.JPasswordField txt_pass_nuevo;
    private javax.swing.JPasswordField txt_pass_nuevo_confirmar;
    // End of variables declaration//GEN-END:variables

    
}
