/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import javax.swing.ImageIcon;

/**
 *
 * @author Luis Estrada
 */
public class mdl_SubMenuReporte extends java.awt.Dialog {

    /**
     * Creates new form mdl_SubMenuReporte
     */
    public mdl_SubMenuReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_reporte = new javax.swing.JPanel();
        btn_cliente = new javax.swing.JButton();
        brn_puntos = new javax.swing.JButton();
        btn_graficas = new javax.swing.JButton();
        jl_TituloPrincipal = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(577, 357));
        setMinimumSize(new java.awt.Dimension(577, 357));
        setTitle("Menú de Reportes y Graficas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jpanel_reporte.setMinimumSize(new java.awt.Dimension(680, 530));
        jpanel_reporte.setLayout(null);

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/cliente.png"))); // NOI18N
        btn_cliente.setText("Clientes");
        jpanel_reporte.add(btn_cliente);
        btn_cliente.setBounds(220, 120, 160, 60);

        brn_puntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/estadistica puntos.png"))); // NOI18N
        brn_puntos.setText("Puntos");
        jpanel_reporte.add(brn_puntos);
        brn_puntos.setBounds(220, 200, 160, 60);

        btn_graficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/grafica.png"))); // NOI18N
        btn_graficas.setText("Graficas");
        jpanel_reporte.add(btn_graficas);
        btn_graficas.setBounds(220, 270, 160, 60);

        jl_TituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_TituloPrincipal.setText("Menú de Reportes");
        jpanel_reporte.add(jl_TituloPrincipal);
        jl_TituloPrincipal.setBounds(180, 50, 230, 30);

        add(jpanel_reporte);
        jpanel_reporte.setBounds(0, 0, 580, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_SubMenuReporte dialog = new mdl_SubMenuReporte(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_puntos;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_graficas;
    private javax.swing.JLabel jl_TituloPrincipal;
    private javax.swing.JPanel jpanel_reporte;
    // End of variables declaration//GEN-END:variables
}
