/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import javax.swing.ImageIcon;

/**
 *
 * @author Luis Estrada
 */
public class mdl_MenuConfiguracion extends java.awt.Dialog {

    /**
     * Creates new form mdl_MenuConfiguracion
     */
    public mdl_MenuConfiguracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario        
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btn_realizarRifa = new javax.swing.JButton();
        btn_reinicioPuntos = new javax.swing.JButton();
        btn_PorcentajePuntos = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(587, 383));
        setMinimumSize(new java.awt.Dimension(587, 383));
        setModal(true);
        setTitle("Configuración del Sistema");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jPanel2.setLayout(null);

        btn_realizarRifa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/rifa.png"))); // NOI18N
        btn_realizarRifa.setText("Realizar Rifa");
        btn_realizarRifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_realizarRifaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_realizarRifa);
        btn_realizarRifa.setBounds(190, 120, 190, 60);

        btn_reinicioPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/limpiar.png"))); // NOI18N
        btn_reinicioPuntos.setText("Reinicio de Puntos");
        btn_reinicioPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_reinicioPuntosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_reinicioPuntos);
        btn_reinicioPuntos.setBounds(190, 200, 190, 60);

        btn_PorcentajePuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/dato puntos.png"))); // NOI18N
        btn_PorcentajePuntos.setText("Porcentaje de Puntos");
        btn_PorcentajePuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PorcentajePuntosActionPerformed(evt);
            }
        });
        jPanel2.add(btn_PorcentajePuntos);
        btn_PorcentajePuntos.setBounds(190, 290, 190, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Configuración del Sistema");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(130, 50, 340, 40);

        add(jPanel2);
        jPanel2.setBounds(0, 0, 600, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_realizarRifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_realizarRifaActionPerformed
        frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
        mdl_Rifa ver=new mdl_Rifa(frmMenuPrincipal,true);
        ver.setVisible(true); // visible ventana del objeto
    }//GEN-LAST:event_btn_realizarRifaActionPerformed

    private void btn_reinicioPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_reinicioPuntosActionPerformed
        frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
        mdl_ReinicioPuntos  ver=new mdl_ReinicioPuntos(frmMenuPrincipal,true);
        ver.setVisible(true); // visible ventana del objeto
    }//GEN-LAST:event_btn_reinicioPuntosActionPerformed

    private void btn_PorcentajePuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PorcentajePuntosActionPerformed
        frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
        mdl_ConfiguracionPorcentajePuntos  ver=new mdl_ConfiguracionPorcentajePuntos(frmMenuPrincipal,true);
        ver.setVisible(true); // visible ventana del objeto
    }//GEN-LAST:event_btn_PorcentajePuntosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_MenuConfiguracion dialog = new mdl_MenuConfiguracion(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_PorcentajePuntos;
    private javax.swing.JButton btn_realizarRifa;
    private javax.swing.JButton btn_reinicioPuntos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
