/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import Conexion.Conexion;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Luis Estrada
 */
public class mdl_SubMenuReporte extends java.awt.Dialog {

    /**
     * Creates new form mdl_SubMenuReporte
     */
    public mdl_SubMenuReporte(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanel_reporte = new javax.swing.JPanel();
        btn_cliente = new javax.swing.JButton();
        brn_puntos = new javax.swing.JButton();
        btn_graficas = new javax.swing.JButton();
        jl_TituloPrincipal = new javax.swing.JLabel();
        brn_rangoDeEdad = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(577, 357));
        setMinimumSize(new java.awt.Dimension(577, 357));
        setTitle("Menú de Reportes y Graficas");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jpanel_reporte.setMinimumSize(new java.awt.Dimension(680, 530));
        jpanel_reporte.setLayout(null);

        btn_cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/cliente.png"))); // NOI18N
        btn_cliente.setText("Clientes");
        btn_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clienteActionPerformed(evt);
            }
        });
        jpanel_reporte.add(btn_cliente);
        btn_cliente.setBounds(220, 120, 160, 60);

        brn_puntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/estadistica puntos.png"))); // NOI18N
        brn_puntos.setText("Puntos");
        brn_puntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_puntosActionPerformed(evt);
            }
        });
        jpanel_reporte.add(brn_puntos);
        brn_puntos.setBounds(40, 120, 160, 60);

        btn_graficas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/grafica.png"))); // NOI18N
        btn_graficas.setText("Graficas");
        jpanel_reporte.add(btn_graficas);
        btn_graficas.setBounds(220, 270, 160, 60);

        jl_TituloPrincipal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jl_TituloPrincipal.setText("Menú de Reportes");
        jpanel_reporte.add(jl_TituloPrincipal);
        jl_TituloPrincipal.setBounds(180, 50, 230, 30);

        brn_rangoDeEdad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/estadistica puntos.png"))); // NOI18N
        brn_rangoDeEdad.setText("Rango de Edad");
        brn_rangoDeEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brn_rangoDeEdadActionPerformed(evt);
            }
        });
        jpanel_reporte.add(brn_rangoDeEdad);
        brn_rangoDeEdad.setBounds(220, 200, 160, 60);

        add(jpanel_reporte);
        jpanel_reporte.setBounds(0, 0, 580, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void btn_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clienteActionPerformed
        Conexion con= new Conexion();
        
        try{
            con.getConexion();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error" + e.getMessage(),
                    "Error de conexion", JOptionPane.ERROR_MESSAGE);
        }
        
        URL archivo = this.getClass().getResource("/reportes/report_cliente_x_zona.jasper");
        
        try {
             frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
       
            JasperReport jr = (JasperReport) JRLoader.loadObject(archivo);
            JasperPrint jp = JasperFillManager.fillReport(jr,null, Conexion.getConexion());
            JasperViewer jv = new JasperViewer(jp,false);
            JDialog dialog = new JDialog(this);
            dialog.setContentPane(jv.getContentPane());
            dialog.setSize(jv.getSize());
            dialog.setTitle("Visor de Reporte Farmacia Regis - Las Casitas");
            dialog.setIconImage(Toolkit.getDefaultToolkit().getImage(
            getClass().getResource("../imgSP/icono.png")));
            dialog.setVisible(true);
        } catch (JRException ex) {
            Logger.getLogger(mdl_SubMenuReporte.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
        
        
    }//GEN-LAST:event_btn_clienteActionPerformed

    private void brn_puntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_puntosActionPerformed
        
    }//GEN-LAST:event_brn_puntosActionPerformed

    private void brn_rangoDeEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brn_rangoDeEdadActionPerformed
        frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
        mdl_rangoEdad ver=new mdl_rangoEdad(frmMenuPrincipal,true);
        ver.setVisible(true); // visible ventana del objeto
    }//GEN-LAST:event_brn_rangoDeEdadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_SubMenuReporte dialog = new mdl_SubMenuReporte(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brn_puntos;
    private javax.swing.JButton brn_rangoDeEdad;
    private javax.swing.JButton btn_cliente;
    private javax.swing.JButton btn_graficas;
    private javax.swing.JLabel jl_TituloPrincipal;
    private javax.swing.JPanel jpanel_reporte;
    // End of variables declaration//GEN-END:variables
}
