/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

import static Conexion.Conexion.consulta;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Vector;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class mdl_ParametrosImpresion extends javax.swing.JDialog {

    /**
     * Creates new form mdl_parametrosImpresion
     */
    public mdl_ParametrosImpresion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
        
        lblMensaje.setVisible(false);
        cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParametrosImpresion = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblParametros = new javax.swing.JTable();
        lblMensaje = new javax.swing.JLabel();
        btnAgregarParametros = new javax.swing.JButton();
        btnEditarParametros = new javax.swing.JButton();
        btnEliminarParametros = new javax.swing.JButton();
        btnActivarParametros = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Parametros para impresión");
        setMaximumSize(new java.awt.Dimension(735, 320));
        setMinimumSize(new java.awt.Dimension(735, 320));

        pnlParametrosImpresion.setLayout(null);

        tblParametros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Altura (mm)", "Anchura (mm)", "Estado", "id"
            }
        ));
        jScrollPane1.setViewportView(tblParametros);
        if (tblParametros.getColumnModel().getColumnCount() > 0) {
            tblParametros.getColumnModel().getColumn(3).setMinWidth(0);
            tblParametros.getColumnModel().getColumn(3).setPreferredWidth(0);
            tblParametros.getColumnModel().getColumn(3).setMaxWidth(0);
        }

        pnlParametrosImpresion.add(jScrollPane1);
        jScrollPane1.setBounds(10, 92, 540, 210);

        lblMensaje.setText("No hay parametros de impresion para el tamaño de hoja.");
        pnlParametrosImpresion.add(lblMensaje);
        lblMensaje.setBounds(20, 60, 334, 16);

        btnAgregarParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/agregar.png"))); // NOI18N
        btnAgregarParametros.setText("Agregar");
        btnAgregarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarParametrosActionPerformed(evt);
            }
        });
        pnlParametrosImpresion.add(btnAgregarParametros);
        btnAgregarParametros.setBounds(560, 150, 140, 40);

        btnEditarParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/modificar.png"))); // NOI18N
        btnEditarParametros.setText("Editar");
        btnEditarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarParametrosActionPerformed(evt);
            }
        });
        pnlParametrosImpresion.add(btnEditarParametros);
        btnEditarParametros.setBounds(560, 200, 140, 40);

        btnEliminarParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/deshabilitar.png"))); // NOI18N
        btnEliminarParametros.setText("Eliminar");
        btnEliminarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarParametrosActionPerformed(evt);
            }
        });
        pnlParametrosImpresion.add(btnEliminarParametros);
        btnEliminarParametros.setBounds(560, 260, 140, 40);

        btnActivarParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/asignar.png"))); // NOI18N
        btnActivarParametros.setText("Activar");
        btnActivarParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarParametrosActionPerformed(evt);
            }
        });
        pnlParametrosImpresion.add(btnActivarParametros);
        btnActivarParametros.setBounds(560, 90, 140, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Parametros para impresión");
        pnlParametrosImpresion.add(jLabel2);
        jLabel2.setBounds(210, 20, 340, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(pnlParametrosImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlParametrosImpresion, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarParametrosActionPerformed
        // TODO add your handling code here:
        frmMenuPrincipal frmMenuPrincipal =  new frmMenuPrincipal();
        mdl_TamanoPapel  ver=new mdl_TamanoPapel(frmMenuPrincipal,true);
        ver.setVisible(true); // visible ventana del objeto

    }//GEN-LAST:event_btnAgregarParametrosActionPerformed

    private void btnEditarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarParametrosActionPerformed
        try {
            int row = tblParametros.getSelectedRow();
            int idParametros = (int)tblParametros.getValueAt(row, 3);

            ResultSet res = consulta("SELECT * FROM Parametro_Impresion\n" +
                                     "WHERE id_parametro_impresion = '" + idParametros + "'; ");

            frmMenuPrincipal menuprin = new frmMenuPrincipal();
            mdl_TamanoPapel tamanoPapel = new mdl_TamanoPapel(menuprin, true);

            try {
                while (res.next()) {
                    
                    tamanoPapel.recibirId(idParametros);
                    tamanoPapel.setVisible(true);
                }

            } catch (SQLException e) {

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro");

        }

        /*frmMenuPrincipal frmMenuPrincipal = new frmMenuPrincipal();
        mdl_CanjeoPuntos canjear = new mdl_CanjeoPuntos(frmMenuPrincipal, true);
        canjear.setVisible(true); // visible ventana del objeto*/
    }//GEN-LAST:event_btnEditarParametrosActionPerformed

    private void btnEliminarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarParametrosActionPerformed
        try {
            int row = tblParametros.getSelectedRow();
            int idParametros = (int)tblParametros.getValueAt(row, 3);
            
            Procedimientos.ProcedimientosParametrosImpresion.eliminarParametros(idParametros);
            cargarTabla();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro: ");

        }
    }//GEN-LAST:event_btnEliminarParametrosActionPerformed

    private void btnActivarParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarParametrosActionPerformed
        try {
            int row = tblParametros.getSelectedRow();
            int idParametros = (int)tblParametros.getValueAt(row, 3);
            
            Procedimientos.ProcedimientosParametrosImpresion.activarParametro(idParametros);
            cargarTabla();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Seleccione un registro: ");

        }
    }//GEN-LAST:event_btnActivarParametrosActionPerformed

    public void cargarTabla(){
        int contador= 0;
        DefaultTableModel modelo = (DefaultTableModel) tblParametros.getModel();
        modelo.setRowCount(0);
        ResultSet respuesta = Conexion.Conexion.consulta("SELECT altura, anchura, estado, id_parametro_impresion FROM Parametro_Impresion");
        try{
            while (respuesta.next()){
                Vector v  = new Vector();
                v.add(respuesta.getDouble(1));
                v.add(respuesta.getDouble(2));
                v.add(respuesta.getString(3));
                v.add(respuesta.getInt(4));
                
                modelo.addRow(v);
                tblParametros.setModel(modelo);
                contador+=1;
            }
            if(contador==0){
                //JOptionPane.showMessageDialog(null, "No hay parametros de imp con puntos vencidos");
                lblMensaje.setVisible(true);
                lblMensaje.setForeground(Color.RED);
            }
            //System.out.println(contador);
        
        }catch(SQLException e){
            System.out.println(e);
        }
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdl_ParametrosImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdl_ParametrosImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdl_ParametrosImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdl_ParametrosImpresion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_ParametrosImpresion dialog = new mdl_ParametrosImpresion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarParametros;
    private javax.swing.JButton btnAgregarParametros;
    private javax.swing.JButton btnEditarParametros;
    private javax.swing.JButton btnEliminarParametros;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JPanel pnlParametrosImpresion;
    private javax.swing.JTable tblParametros;
    // End of variables declaration//GEN-END:variables
}
