/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmArea;

/**
 *
 * @author Luis Estrada
 */
import Clases.Validar;
import Clases.Zona;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JDayChooser;
import java.awt.Component;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

public class mdl_SubMenuCliente extends java.awt.Dialog {

    Validar v = new Validar();
    private JTextField id = new JTextField();
    ResultSet res = null;
    int cont = 0;
    //Variable para capturar el estado
    String estado = "";
  

    public mdl_SubMenuCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null); //para ponerse en el centro
        this.setResizable(false); //Desactivar botón maximizar de una ventana
        setIconImage(new ImageIcon(getClass().getResource("../imgSP/icono.png")).getImage()); //cambia el icono del formulario
        //cargarZonas();

        v.ValidarSoloLetras(txt_primerNombre);
        v.ValidarSoloLetras(txt_segundoNombre);
        v.ValidarSoloLetras(txt_primerApellido);
        v.ValidarSoloLetras(txt_segundoApellido);
        v.ValidarTelefono(txt_telefono1);
        v.ValidarTelefono(txt_telefono2);
        v.ValidarTelefono(txt_telefono3);
        v.ValidarIdentidad(txt_identidad);
        v.limitarCaracteres(txt_telefono1, 13);
        v.limitarCaracteres(txt_telefono2, 13);
        v.limitarCaracteres(txt_telefono3, 13);
        v.limitarCaracteres(txt_identidad, 15);
        v.validarModificacionFecha(jD_fechaNac, btn_editarCliente);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo_genero = new javax.swing.ButtonGroup();
        jpanel_AreaSubMenu = new javax.swing.JPanel();
        jpanel_datos1 = new javax.swing.JPanel();
        jL_primerNombre = new javax.swing.JLabel();
        jL_segundoNombre = new javax.swing.JLabel();
        jL_primerApellido = new javax.swing.JLabel();
        jL_segundoApellido = new javax.swing.JLabel();
        jL_identidad = new javax.swing.JLabel();
        jL_sexo = new javax.swing.JLabel();
        jL_telefono = new javax.swing.JLabel();
        txt_primerNombre = new javax.swing.JTextField();
        txt_segundoNombre = new javax.swing.JTextField();
        txt_primerApellido = new javax.swing.JTextField();
        txt_segundoApellido = new javax.swing.JTextField();
        txt_identidad = new javax.swing.JTextField();
        txt_telefono1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_telefono2 = new javax.swing.JTextField();
        txt_telefono3 = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        jL_email = new javax.swing.JLabel();
        jRadioButtonFemenino = new javax.swing.JRadioButton();
        jRadioButtonMasculino = new javax.swing.JRadioButton();
        btn_editarCliente = new javax.swing.JButton();
        btn_desactivarCliente = new javax.swing.JButton();
        btn_imprimirDireccion = new javax.swing.JButton();
        btn_imprimirPuntos = new javax.swing.JButton();
        jpanel_datos2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txt_puntosRegis = new javax.swing.JTextField();
        jL_vencimiento = new javax.swing.JLabel();
        txt_vencimiento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_puntoRifa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jD_fechaNac = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_datalleDireccion = new javax.swing.JTextArea();
        jC_zona = new javax.swing.JComboBox<>();
        btn_habilitarcliente = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(700, 450));
        setMinimumSize(new java.awt.Dimension(700, 450));
        setTitle("Gestion de Cliente");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });
        setLayout(null);

        jpanel_AreaSubMenu.setMaximumSize(new java.awt.Dimension(700, 450));
        jpanel_AreaSubMenu.setMinimumSize(new java.awt.Dimension(700, 450));
        jpanel_AreaSubMenu.setPreferredSize(new java.awt.Dimension(700, 450));
        jpanel_AreaSubMenu.setLayout(null);

        jpanel_datos1.setLayout(null);

        jL_primerNombre.setText("Primer Nombre:");
        jpanel_datos1.add(jL_primerNombre);
        jL_primerNombre.setBounds(0, 10, 100, 14);

        jL_segundoNombre.setText("Segundo Nombre:");
        jpanel_datos1.add(jL_segundoNombre);
        jL_segundoNombre.setBounds(0, 40, 109, 14);

        jL_primerApellido.setText("Primer Apellido:");
        jpanel_datos1.add(jL_primerApellido);
        jL_primerApellido.setBounds(0, 70, 100, 14);

        jL_segundoApellido.setText("Segundo Apellido:");
        jpanel_datos1.add(jL_segundoApellido);
        jL_segundoApellido.setBounds(0, 100, 109, 14);

        jL_identidad.setText("Identidad:");
        jpanel_datos1.add(jL_identidad);
        jL_identidad.setBounds(0, 130, 100, 14);

        jL_sexo.setText("Sexo :");
        jpanel_datos1.add(jL_sexo);
        jL_sexo.setBounds(0, 160, 100, 14);

        jL_telefono.setText("Telefono 1:");
        jpanel_datos1.add(jL_telefono);
        jL_telefono.setBounds(0, 190, 100, 14);

        txt_primerNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_primerNombreMouseClicked(evt);
            }
        });
        txt_primerNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_primerNombreKeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_primerNombre);
        txt_primerNombre.setBounds(110, 10, 180, 24);

        txt_segundoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_segundoNombreActionPerformed(evt);
            }
        });
        txt_segundoNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_segundoNombreKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_segundoNombreKeyTyped(evt);
            }
        });
        jpanel_datos1.add(txt_segundoNombre);
        txt_segundoNombre.setBounds(110, 40, 180, 24);

        txt_primerApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_primerApellidoKeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_primerApellido);
        txt_primerApellido.setBounds(110, 70, 180, 24);

        txt_segundoApellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_segundoApellidoKeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_segundoApellido);
        txt_segundoApellido.setBounds(110, 100, 180, 24);

        txt_identidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_identidadKeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_identidad);
        txt_identidad.setBounds(110, 130, 180, 24);

        txt_telefono1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono1KeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_telefono1);
        txt_telefono1.setBounds(110, 190, 180, 24);

        jLabel1.setText("Telefono 2:");
        jpanel_datos1.add(jLabel1);
        jLabel1.setBounds(0, 220, 100, 14);

        jLabel2.setText("Telefono 3:");
        jpanel_datos1.add(jLabel2);
        jLabel2.setBounds(0, 250, 100, 14);

        txt_telefono2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono2KeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_telefono2);
        txt_telefono2.setBounds(110, 220, 180, 24);

        txt_telefono3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_telefono3KeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_telefono3);
        txt_telefono3.setBounds(110, 250, 180, 24);

        txt_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_emailFocusLost(evt);
            }
        });
        txt_email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_emailKeyPressed(evt);
            }
        });
        jpanel_datos1.add(txt_email);
        txt_email.setBounds(110, 280, 180, 24);

        jL_email.setText("Email:");
        jpanel_datos1.add(jL_email);
        jL_email.setBounds(0, 280, 100, 14);

        grupo_genero.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setText("F");
        jRadioButtonFemenino.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jRadioButtonFemenino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonFemeninoMouseClicked(evt);
            }
        });
        jRadioButtonFemenino.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRadioButtonFemeninoKeyPressed(evt);
            }
        });
        jpanel_datos1.add(jRadioButtonFemenino);
        jRadioButtonFemenino.setBounds(110, 160, 40, 23);

        grupo_genero.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setText("M");
        jRadioButtonMasculino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jRadioButtonMasculinoMouseClicked(evt);
            }
        });
        jRadioButtonMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMasculinoActionPerformed(evt);
            }
        });
        jpanel_datos1.add(jRadioButtonMasculino);
        jRadioButtonMasculino.setBounds(150, 160, 50, 23);

        jpanel_AreaSubMenu.add(jpanel_datos1);
        jpanel_datos1.setBounds(20, 90, 310, 350);

        btn_editarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/guardar.png"))); // NOI18N
        btn_editarCliente.setText("Guardar");
        btn_editarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_editarCliente.setEnabled(false);
        btn_editarCliente.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_editarCliente.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_editarCliente.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_editarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarClienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_editarCliente);
        btn_editarCliente.setBounds(20, 30, 140, 40);

        btn_desactivarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/inhabilitar.png"))); // NOI18N
        btn_desactivarCliente.setText("Deshabilitar");
        btn_desactivarCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_desactivarCliente.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_desactivarCliente.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_desactivarCliente.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_desactivarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_desactivarClienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_desactivarCliente);
        btn_desactivarCliente.setBounds(190, 30, 140, 40);

        btn_imprimirDireccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/dato entrega.png"))); // NOI18N
        btn_imprimirDireccion.setText("Imprimir dirección");
        btn_imprimirDireccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_imprimirDireccion.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_imprimirDireccion.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_imprimirDireccion.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_imprimirDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirDireccionActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_imprimirDireccion);
        btn_imprimirDireccion.setBounds(360, 30, 140, 40);

        btn_imprimirPuntos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/dato puntos.png"))); // NOI18N
        btn_imprimirPuntos.setText("Imprimir puntos");
        btn_imprimirPuntos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_imprimirPuntos.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_imprimirPuntos.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_imprimirPuntos.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_imprimirPuntos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_imprimirPuntosActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_imprimirPuntos);
        btn_imprimirPuntos.setBounds(530, 30, 140, 40);

        jpanel_datos2.setLayout(null);

        jLabel9.setText("Puntos Regis:");
        jpanel_datos2.add(jLabel9);
        jLabel9.setBounds(22, 214, 130, 14);

        txt_puntosRegis.setEditable(false);
        txt_puntosRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntosRegisActionPerformed(evt);
            }
        });
        jpanel_datos2.add(txt_puntosRegis);
        txt_puntosRegis.setBounds(130, 210, 180, 24);

        jL_vencimiento.setText("Vencimiento:");
        jpanel_datos2.add(jL_vencimiento);
        jL_vencimiento.setBounds(22, 244, 130, 14);

        txt_vencimiento.setEditable(false);
        txt_vencimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_vencimientoActionPerformed(evt);
            }
        });
        jpanel_datos2.add(txt_vencimiento);
        txt_vencimiento.setBounds(130, 240, 180, 24);

        jLabel11.setText("Puntos rifa:");
        jpanel_datos2.add(jLabel11);
        jLabel11.setBounds(22, 279, 120, 14);

        txt_puntoRifa.setEditable(false);
        txt_puntoRifa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_puntoRifaActionPerformed(evt);
            }
        });
        jpanel_datos2.add(txt_puntoRifa);
        txt_puntoRifa.setBounds(130, 270, 180, 24);

        jLabel3.setText("Fecha Nacimiento:");
        jpanel_datos2.add(jLabel3);
        jLabel3.setBounds(22, 11, 130, 14);

        jD_fechaNac.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jD_fechaNacFocusGained(evt);
            }
        });
        jD_fechaNac.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jD_fechaNacMouseClicked(evt);
            }
        });
        jD_fechaNac.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jD_fechaNacKeyPressed(evt);
            }
        });
        jpanel_datos2.add(jD_fechaNac);
        jD_fechaNac.setBounds(130, 10, 182, 24);

        jLabel4.setText("Zona:");
        jpanel_datos2.add(jLabel4);
        jLabel4.setBounds(22, 53, 130, 14);

        jLabel5.setText("Dirección:");
        jpanel_datos2.add(jLabel5);
        jLabel5.setBounds(20, 90, 130, 14);

        txt_datalleDireccion.setColumns(20);
        txt_datalleDireccion.setRows(5);
        txt_datalleDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_datalleDireccionKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(txt_datalleDireccion);

        jpanel_datos2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 90, 182, 96);

        jC_zona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jC_zonaMouseClicked(evt);
            }
        });
        jC_zona.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jC_zonaKeyPressed(evt);
            }
        });
        jpanel_datos2.add(jC_zona);
        jC_zona.setBounds(130, 50, 182, 20);

        jpanel_AreaSubMenu.add(jpanel_datos2);
        jpanel_datos2.setBounds(360, 90, 320, 340);

        btn_habilitarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgSP/habilitar.png"))); // NOI18N
        btn_habilitarcliente.setText("Habilitar");
        btn_habilitarcliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_habilitarcliente.setMaximumSize(new java.awt.Dimension(140, 40));
        btn_habilitarcliente.setMinimumSize(new java.awt.Dimension(140, 40));
        btn_habilitarcliente.setPreferredSize(new java.awt.Dimension(140, 40));
        btn_habilitarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_habilitarclienteActionPerformed(evt);
            }
        });
        jpanel_AreaSubMenu.add(btn_habilitarcliente);
        btn_habilitarcliente.setBounds(190, 30, 140, 40);

        add(jpanel_AreaSubMenu);
        jpanel_AreaSubMenu.setBounds(0, 20, 700, 450);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Closes the dialog
     */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void txt_primerNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_segundoNombre().requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(getTxt_primerNombre());
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_primerNombreKeyPressed

    private void txt_segundoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_segundoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_segundoNombreActionPerformed

    private void txt_segundoNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoNombreKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            System.out.println(evt.getKeyCode());
            getTxt_primerApellido().requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(getTxt_segundoNombre());
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_segundoNombreKeyPressed

    private void txt_primerApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_primerApellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_segundoApellido().requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(getTxt_primerApellido());
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_primerApellidoKeyPressed

    private void txt_segundoApellidoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoApellidoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_identidad().requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(getTxt_segundoApellido());
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_segundoApellidoKeyPressed

    private void txt_identidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_identidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jRadioButtonFemenino.requestFocus();
        } else if (evt.getKeyCode() == KeyEvent.VK_SPACE) {
            v.validarEspacios(getTxt_identidad());
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_identidadKeyPressed

    private void txt_telefono1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono1KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_telefono2().requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_telefono1KeyPressed

    private void txt_telefono2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_telefono3().requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_telefono2KeyPressed

    private void txt_telefono3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_telefono3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_email().requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_telefono3KeyPressed

    private void txt_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_emailFocusLost
        if (!"".equals(txt_email.getText())) {
            if (v.validarCorreo(getTxt_email())) {
                jD_fechaNac.requestFocus();
            } else {
                JOptionPane.showMessageDialog(null, "Correo inválido", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                getTxt_email().requestFocus();
            }
        } else {
            jD_fechaNac.requestFocus();
        }
    }//GEN-LAST:event_txt_emailFocusLost

    private void txt_emailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_emailKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jD_fechaNac.requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_emailKeyPressed

    private void jRadioButtonFemeninoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRadioButtonFemeninoKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_telefono1().requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_jRadioButtonFemeninoKeyPressed


    private void jRadioButtonMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMasculinoActionPerformed

    private void btn_editarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarClienteActionPerformed

        //Validar que no esten vacios los campos requeridos
        if (getTxt_primerNombre().getText().isEmpty() || getTxt_primerApellido().getText().isEmpty() || getTxt_identidad().getText().isEmpty()
                || getTxt_telefono1().getText().isEmpty() || jD_fechaNac.getCalendar() == null
                || jC_zona.getSelectedItem() == null || (jRadioButtonMasculino.isSelected() == false && jRadioButtonFemenino.isSelected() == false)
                || txt_datalleDireccion.getText().isEmpty()) {

            JOptionPane.showMessageDialog(this, "Se dejaron vacios campos que son obligatorios", "Informacion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                res = Conexion.Conexion.consulta("SELECT COUNT(identidad) from persona WHERE identidad='" + txt_identidad.getText() + "'");
                try {
                    while (res.next()) {
                        cont = res.getInt(1);
                    }
                } catch (SQLException e) {
                }
                if (cont > 1) {
                    JOptionPane.showMessageDialog(this, "Este numero de identidad ya está registrado", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    //PREPARO LA FECHA PARA ENVIARLA
                    java.sql.Date fechaNac = new java.sql.Date(jD_fechaNac.getDate().getTime());

                    //Consulto el id de la zona que eligio el usuario para registrarla en la tabla clientes
                    ResultSet respuesta = Zona.consultarIdZona((String) jC_zona.getSelectedItem());
                    int idZona = 0;

                    while (respuesta.next()) {
                        idZona = respuesta.getInt(1);
                    }

                    //Verificar el sexo seleccionado
                    String sexo = "";
                    if (jRadioButtonMasculino.isSelected() == true) {
                        sexo = "M";
                    } else if (jRadioButtonFemenino.isSelected() == true) {
                        sexo = "F";
                    }

                    Procedimientos.ProcedimientosCliente.actualizarCliente(getTxt_primerNombre().getText(), getTxt_segundoNombre().getText(),
                            getTxt_primerApellido().getText(), getTxt_segundoApellido().getText(), getTxt_identidad().getText(), getTxt_email().getText(),
                            sexo, fechaNac, getTxt_telefono1().getText(), getTxt_telefono2().getText(), getTxt_telefono3().getText(),
                            idZona, getTxt_datalleDireccion().getText(), Integer.parseInt(getTxt_puntosRegis().getText()),
                            getTxt_vencimiento().getText(), Integer.parseInt(getTxt_puntoRifa().getText()),
                            Integer.parseInt(getId().getText())
                    );

                    //Limpiar los campos
                    getTxt_primerNombre().setText("");
                    getTxt_segundoNombre().setText("");
                    getTxt_primerApellido().setText("");
                    getTxt_segundoApellido().setText("");
                    getTxt_identidad().setText("");
                    getTxt_email().setText("");
                    getTxt_telefono1().setText("");
                    getTxt_telefono2().setText("");
                    getTxt_telefono3().setText("");
                    jRadioButtonMasculino.setSelected(false);
                    jRadioButtonFemenino.setSelected(false);
                    jD_fechaNac.setCalendar(null);
                    jC_zona.setSelectedIndex(0);
                    getTxt_datalleDireccion().setText("");
                    getTxt_primerNombre().requestFocus();
                    getTxt_segundoNombre().requestFocus();
                    getTxt_primerApellido().requestFocus();
                    getTxt_segundoApellido().requestFocus();
                    getTxt_identidad().requestFocus();
                    getTxt_email().requestFocus();
                    getTxt_telefono1().requestFocus();
                    getTxt_telefono2().requestFocus();
                    getTxt_telefono3().requestFocus();
                    jD_fechaNac.requestFocus();
                    jC_zona.requestFocus();
                    getTxt_primerNombre().requestFocus();

                    JOptionPane.showMessageDialog(this, "Registro actualizado");
                    res.close();//Cierro la conexio a la base de datos
                }
            } catch (SQLException e) {
            }
        }
    }//GEN-LAST:event_btn_editarClienteActionPerformed

    private void btn_desactivarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_desactivarClienteActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea deshabilitar este cliente?");
        if (pregunta == 0) {
            try {
                int idpersona = Integer.parseInt(getId().getText());//Convertir a entero para enviarlo
                Procedimientos.ProcedimientosCliente.deshabilitarCliente(idpersona);
                JOptionPane.showMessageDialog(null, "El cliente ha sido deshabilitado");
                btn_habilitarcliente.setVisible(true);
                btn_desactivarCliente.setVisible(false);
            } catch (SQLException e) {

            }
        } else if (pregunta == 1) {
            JOptionPane.showMessageDialog(null, "El cliente no ha sido deshabilitado");
        } else {
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
        }
    }//GEN-LAST:event_btn_desactivarClienteActionPerformed

    private void btn_imprimirDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirDireccionActionPerformed
        if ((txt_primerNombre.getText() + txt_segundoNombre.getText() + txt_primerApellido.getText()
                + txt_segundoApellido.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Datos vacios");
        } else {
            int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea imprimir direccion?", "Confirmar impresión",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (eleccion == JOptionPane.NO_OPTION) {
            } else {
                frmMenuPrincipal mp = new frmMenuPrincipal();
                mdl_ImprimirDireccion dir = new mdl_ImprimirDireccion(mp, true);

                String nombre = this.txt_primerNombre.getText() + " " + this.txt_segundoNombre.getText()
                        + " " + this.txt_primerApellido.getText() + " " + this.txt_segundoApellido.getText(),
                        telefono = this.txt_telefono1.getText(),
                        sexo = null,
                        direccion = this.txt_datalleDireccion.getText();

                if (this.jRadioButtonMasculino.isSelected() == true) {
                    sexo = "Masculino";
                } else {
                    sexo = "Femenino";
                }

                dir.cargarDatos(nombre, telefono, sexo, direccion);
                dir.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_imprimirDireccionActionPerformed

    public void cargarZonas(String zona) {
        ResultSet zonas = Zona.mostrarZonas();
        //LLenamos nuestro ComboBox
        jC_zona.addItem(zona);
        try {
            while (zonas.next()) {
                if (!zonas.getString("zona").equals(zona)) {
                    jC_zona.addItem(zonas.getString("zona"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(mdl_SubMenuCliente.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    //Metodo para llenar los campos     
    public void llenarCampos(String pnombre, String snombre, String papellido, String sapellido, String identidad,
            String sexo, String telefono1, String telefono2, String telefono3, String correo,
            Date fechaNac, String detalleDireccion, String puntos_actuales, String puntos_rifa,
            String fechaVencimiento, String id, String estado) {
        this.getTxt_primerNombre().setText(pnombre);
        this.getTxt_segundoNombre().setText(snombre);
        this.getTxt_primerApellido().setText(papellido);
        this.getTxt_segundoApellido().setText(sapellido);
        this.getTxt_identidad().setText(identidad);
        if ("M".equals(sexo)) {
            this.jRadioButtonMasculino.setSelected(true);
        } else {
            this.jRadioButtonFemenino.setSelected(true);
        }
        this.getTxt_telefono1().setText(telefono1);
        this.getTxt_telefono2().setText(telefono2);
        this.getTxt_telefono3().setText(telefono3);
        this.getTxt_email().setText(correo);
        this.jD_fechaNac.setDate(fechaNac);
        this.getTxt_datalleDireccion().setText(detalleDireccion);
        this.getTxt_puntosRegis().setText(puntos_actuales);
        this.getTxt_puntoRifa().setText(puntos_rifa);
        this.getTxt_vencimiento().setText(fechaVencimiento);
        this.getId().setText(id);
        this.estado = estado;

        if ("A".equals(estado)) {
            btn_habilitarcliente.setVisible(false);
            btn_desactivarCliente.setVisible(true);
        } else {
            btn_habilitarcliente.setVisible(true);
            btn_desactivarCliente.setVisible(false);
        }

    }

    //Metodo para mostrar y ocultar botones de habilitar y desabilitar
    public void habilitarDeshabilitar() {

    }

    private void btn_imprimirPuntosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_imprimirPuntosActionPerformed
        if ((txt_primerNombre.getText() + txt_segundoNombre.getText() + txt_primerApellido.getText()
                + txt_segundoApellido.getText()).isEmpty()) {
            JOptionPane.showMessageDialog(null, "Datos vacios");
        } else {
            int eleccion = JOptionPane.showConfirmDialog(null, "¿Desea imprimir puntos?", "Confirmar impresión",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (eleccion == JOptionPane.NO_OPTION) {
            } else {
                frmMenuPrincipal mp = new frmMenuPrincipal();
                mdl_ImprimirPuntos dir = new mdl_ImprimirPuntos(mp, true);

                String nombre = this.txt_primerNombre.getText() + " " + this.txt_segundoNombre.getText()
                        + " " + this.txt_primerApellido.getText() + " " + this.txt_segundoApellido.getText(),
                        puntosRegis = this.txt_puntosRegis.getText(),
                        puntosRifa = this.txt_puntoRifa.getText(),
                        vencimiento = this.txt_vencimiento.getText();

                dir.cargarDatos(nombre, puntosRegis, puntosRifa, vencimiento);
                dir.setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_imprimirPuntosActionPerformed

    private void txt_puntosRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntosRegisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntosRegisActionPerformed

    private void txt_vencimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_vencimientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_vencimientoActionPerformed

    private void txt_puntoRifaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_puntoRifaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_puntoRifaActionPerformed

    private void jD_fechaNacKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jD_fechaNacKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jC_zona.requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_jD_fechaNacKeyPressed

    private void txt_datalleDireccionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_datalleDireccionKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_primerNombre().requestFocus();
        } else if (evt.getKeyCode() != 0) {
            btn_editarCliente.setEnabled(true);
        }
    }//GEN-LAST:event_txt_datalleDireccionKeyPressed

    private void jC_zonaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jC_zonaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            getTxt_datalleDireccion().requestFocus();
        }
    }//GEN-LAST:event_jC_zonaKeyPressed

    private void btn_habilitarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_habilitarclienteActionPerformed
        int pregunta = JOptionPane.showConfirmDialog(null, "¿Realmente desea habilitar este cliente?");
        if (pregunta == 0) {
            try {
                int idpersona = Integer.parseInt(getId().getText());//Convertir a entero para enviarlo
                Procedimientos.ProcedimientosCliente.habilitarCliente(idpersona);
                JOptionPane.showMessageDialog(null, "El cliente ha sido habilitado");
                btn_habilitarcliente.setVisible(false);
                btn_desactivarCliente.setVisible(true);
            } catch (SQLException e) {

            }
        } else if (pregunta == 1) {
            JOptionPane.showMessageDialog(null, "El cliente no ha sido habilitado");
        } else {
            JOptionPane.showMessageDialog(null, "Operacion cancelada");
        }
    }//GEN-LAST:event_btn_habilitarclienteActionPerformed

    private void txt_primerNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_primerNombreMouseClicked

    }//GEN-LAST:event_txt_primerNombreMouseClicked

    private void txt_segundoNombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_segundoNombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_segundoNombreKeyTyped

    private void jD_fechaNacMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jD_fechaNacMouseClicked

        btn_editarCliente.setEnabled(true);
    }//GEN-LAST:event_jD_fechaNacMouseClicked

    private void jRadioButtonMasculinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonMasculinoMouseClicked
        btn_editarCliente.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonMasculinoMouseClicked

    private void jC_zonaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jC_zonaMouseClicked
        btn_editarCliente.setEnabled(true);
    }//GEN-LAST:event_jC_zonaMouseClicked

    private void jRadioButtonFemeninoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jRadioButtonFemeninoMouseClicked
        // TODO add your handling code here:
        btn_editarCliente.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonFemeninoMouseClicked

    private void jD_fechaNacFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jD_fechaNacFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jD_fechaNacFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                mdl_SubMenuCliente dialog = new mdl_SubMenuCliente(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_desactivarCliente;
    private javax.swing.JButton btn_editarCliente;
    private javax.swing.JButton btn_habilitarcliente;
    private javax.swing.JButton btn_imprimirDireccion;
    private javax.swing.JButton btn_imprimirPuntos;
    private javax.swing.ButtonGroup grupo_genero;
    private javax.swing.JComboBox<String> jC_zona;
    private com.toedter.calendar.JDateChooser jD_fechaNac;
    private javax.swing.JLabel jL_email;
    private javax.swing.JLabel jL_identidad;
    private javax.swing.JLabel jL_primerApellido;
    private javax.swing.JLabel jL_primerNombre;
    private javax.swing.JLabel jL_segundoApellido;
    private javax.swing.JLabel jL_segundoNombre;
    private javax.swing.JLabel jL_sexo;
    private javax.swing.JLabel jL_telefono;
    private javax.swing.JLabel jL_vencimiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButtonFemenino;
    private javax.swing.JRadioButton jRadioButtonMasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanel_AreaSubMenu;
    private javax.swing.JPanel jpanel_datos1;
    private javax.swing.JPanel jpanel_datos2;
    private javax.swing.JTextArea txt_datalleDireccion;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_identidad;
    private javax.swing.JTextField txt_primerApellido;
    private javax.swing.JTextField txt_primerNombre;
    private javax.swing.JTextField txt_puntoRifa;
    private javax.swing.JTextField txt_puntosRegis;
    private javax.swing.JTextField txt_segundoApellido;
    private javax.swing.JTextField txt_segundoNombre;
    private javax.swing.JTextField txt_telefono1;
    private javax.swing.JTextField txt_telefono2;
    private javax.swing.JTextField txt_telefono3;
    private javax.swing.JTextField txt_vencimiento;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the txt_datalleDireccion
     */
    public javax.swing.JTextArea getTxt_datalleDireccion() {
        return txt_datalleDireccion;
    }

    /**
     * @param txt_datalleDireccion the txt_datalleDireccion to set
     */
    public void setTxt_datalleDireccion(javax.swing.JTextArea txt_datalleDireccion) {
        this.txt_datalleDireccion = txt_datalleDireccion;
    }

    /**
     * @return the txt_email
     */
    public javax.swing.JTextField getTxt_email() {
        return txt_email;
    }

    /**
     * @param txt_email the txt_email to set
     */
    public void setTxt_email(javax.swing.JTextField txt_email) {
        this.txt_email = txt_email;
    }

    /**
     * @return the txt_identidad
     */
    public javax.swing.JTextField getTxt_identidad() {
        return txt_identidad;
    }

    /**
     * @param txt_identidad the txt_identidad to set
     */
    public void setTxt_identidad(javax.swing.JTextField txt_identidad) {
        this.txt_identidad = txt_identidad;
    }

    /**
     * @return the txt_primerApellido
     */
    public javax.swing.JTextField getTxt_primerApellido() {
        return txt_primerApellido;
    }

    /**
     * @param txt_primerApellido the txt_primerApellido to set
     */
    public void setTxt_primerApellido(javax.swing.JTextField txt_primerApellido) {
        this.txt_primerApellido = txt_primerApellido;
    }

    /**
     * @return the txt_primerNombre
     */
    public javax.swing.JTextField getTxt_primerNombre() {
        return txt_primerNombre;
    }

    /**
     * @param txt_primerNombre the txt_primerNombre to set
     */
    public void setTxt_primerNombre(javax.swing.JTextField txt_primerNombre) {
        this.txt_primerNombre = txt_primerNombre;
    }

    /**
     * @return the txt_puntoRifa
     */
    public javax.swing.JTextField getTxt_puntoRifa() {
        return txt_puntoRifa;
    }

    /**
     * @param txt_puntoRifa the txt_puntoRifa to set
     */
    public void setTxt_puntoRifa(javax.swing.JTextField txt_puntoRifa) {
        this.txt_puntoRifa = txt_puntoRifa;
    }

    /**
     * @return the txt_puntosRegis
     */
    public javax.swing.JTextField getTxt_puntosRegis() {
        return txt_puntosRegis;
    }

    /**
     * @param txt_puntosRegis the txt_puntosRegis to set
     */
    public void setTxt_puntosRegis(javax.swing.JTextField txt_puntosRegis) {
        this.txt_puntosRegis = txt_puntosRegis;
    }

    /**
     * @return the txt_segundoApellido
     */
    public javax.swing.JTextField getTxt_segundoApellido() {
        return txt_segundoApellido;
    }

    /**
     * @param txt_segundoApellido the txt_segundoApellido to set
     */
    public void setTxt_segundoApellido(javax.swing.JTextField txt_segundoApellido) {
        this.txt_segundoApellido = txt_segundoApellido;
    }

    /**
     * @return the txt_segundoNombre
     */
    public javax.swing.JTextField getTxt_segundoNombre() {
        return txt_segundoNombre;
    }

    /**
     * @param txt_segundoNombre the txt_segundoNombre to set
     */
    public void setTxt_segundoNombre(javax.swing.JTextField txt_segundoNombre) {
        this.txt_segundoNombre = txt_segundoNombre;
    }

    /**
     * @return the txt_telefono1
     */
    public javax.swing.JTextField getTxt_telefono1() {
        return txt_telefono1;
    }

    /**
     * @param txt_telefono1 the txt_telefono1 to set
     */
    public void setTxt_telefono1(javax.swing.JTextField txt_telefono1) {
        this.txt_telefono1 = txt_telefono1;
    }

    /**
     * @return the txt_telefono2
     */
    public javax.swing.JTextField getTxt_telefono2() {
        return txt_telefono2;
    }

    /**
     * @param txt_telefono2 the txt_telefono2 to set
     */
    public void setTxt_telefono2(javax.swing.JTextField txt_telefono2) {
        this.txt_telefono2 = txt_telefono2;
    }

    /**
     * @return the txt_telefono3
     */
    public javax.swing.JTextField getTxt_telefono3() {
        return txt_telefono3;
    }

    /**
     * @param txt_telefono3 the txt_telefono3 to set
     */
    public void setTxt_telefono3(javax.swing.JTextField txt_telefono3) {
        this.txt_telefono3 = txt_telefono3;
    }

    /**
     * @return the txt_vencimiento
     */
    public javax.swing.JTextField getTxt_vencimiento() {
        return txt_vencimiento;
    }

    /**
     * @param txt_vencimiento the txt_vencimiento to set
     */
    public void setTxt_vencimiento(javax.swing.JTextField txt_vencimiento) {
        this.txt_vencimiento = txt_vencimiento;
    }

    /**
     * @return the id
     */
    public JTextField getId() {
        return id;
    }

    /**
     * @param id the id to set
     */
    public void setId(JTextField id) {
        this.id = id;
    }
}
